'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const CHUNK = 1024 * 1024;
const adapterPath = path.join(__dirname, '../web/game-adapter.js');

function adapterFixture(source, original) {
  const state = { requests: [], mode: 'valid' };
  function selected(start, end) {
    let bytes = original.subarray(start, end + 1);
    if (state.mode === 'short') bytes = bytes.subarray(0, Math.max(0, bytes.length - 1));
    if (state.mode === 'long') bytes = Buffer.concat([bytes, Buffer.from([0])]);
    return bytes;
  }
  class XHR {
    open(method, url, async) {
      assert.equal(method, 'GET'); assert.equal(async, false);
      this.url = new URL(url); assert.equal(this.url.searchParams.get('b64'), '1');
    }
    overrideMimeType(type) { assert.equal(type, 'text/plain; charset=us-ascii'); }
    setRequestHeader(name, value) { assert.equal(name, 'Range'); this.range = value; }
    send() {
      const match = /^bytes=(\d+)-(\d+)$/.exec(this.range); assert.ok(match);
      const start = Number(match[1]), end = Number(match[2]);
      assert.ok(end - start + 1 <= CHUNK);
      state.requests.push([start, end]);
      if (state.onSend) state.onSend();
      this.status = state.mode === 'http' ? 503 : 200;
      this.responseText = state.mode === 'base64' ? '!!invalid!!' : selected(start, end).toString('base64');
    }
  }
  const scope = {
    console, URL, Uint8Array, location: { href: 'https://owner.test/hl2/' },
    XMLHttpRequest: XHR, atob: value => atob(value),
    fetch: async (_url, options) => {
      const match = /^bytes=(\d+)-(\d+)$/.exec(options.headers.Range);
      const bytes = selected(Number(match[1]), Number(match[2]));
      return { ok: true, status: 206, arrayBuffer: async () => bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.length) };
    }
  };
  scope.globalThis = scope;
  const seam = '  global.WasmGameAdapter = Object.freeze({'; assert.ok(source.includes(seam));
  vm.runInNewContext(source.replace(seam,
    '  global.fileMountTest = { syncFetchFile, syncFetchRange, createRangeLazyContents, mountRangeLazyFile, mountLazyWholeFile };\n' + seam), scope);
  return { ...scope.fileMountTest, state, scope };
}

async function retainedFs(filename) {
  let source = fs.readFileSync(filename, 'utf8');
  // The modular loader starts its worker pool just before FS.staticInit.
  // Worker/native execution is outside this filesystem-only harness.
  source = source.replace('PThread.init();', '/* filesystem fixture: no worker pool */');
  const seam = 'FS.staticInit();'; assert.equal(source.split(seam).length, 2, 'expected one retained filesystem initialization seam');
  // Evaluate the generated runtime's actual FS/MEMFS implementation, stopping
  // before Wasm instantiation or native main. No generated bytes are changed
  // on disk or copied into the repository. mmap uses a bounded test allocator.
  source = source.replace(seam, `${seam}
    wasmMemory = new WebAssembly.Memory({ initial: 8 });
    updateMemoryViews();
    mmapAlloc = length => { if (length > 65536) throw Error('fixture mmap too large'); return 65536; };
    return { FS, HEAPU8, HEAP8, updateMemoryViews,
      growFixtureHeap() { wasmMemory.grow(1); updateMemoryViews(); this.HEAPU8 = HEAPU8; this.HEAP8 = HEAP8; }
    };
  `);
  const scope = { console, URL, setTimeout, clearTimeout, window: {},
    document: { currentScript: { src: 'https://owner.test/source-engine.js' } } };
  scope.globalThis = scope;
  vm.runInNewContext(source, scope, { filename: 'retained-fs-in-memory.js' });
  const module = await scope.createSourceEngineModule({ noInitialRun: true });
  module.FS.mkdirTree('/game/hl2');
  module.FS.ignorePermissions = false;
  return module;
}

async function run(source = fs.readFileSync(adapterPath, 'utf8')) {
  const binary = Buffer.alloc(CHUNK + 259);
  for (let i = 0; i < binary.length; i++) binary[i] = i & 255;
  binary.set([0xff, 0xfe, 0x00, 0x00, 0xef, 0xbb, 0xbf], 0);
  const binaryFixture = adapterFixture(source, binary);
  assert.deepEqual(Buffer.from(binaryFixture.syncFetchFile('/owner/binary', binary.length)), binary,
    'UTF-16/UTF-8 BOM patterns, NULs and all byte values must survive synchronous reads');
  assert.deepEqual(binaryFixture.state.requests, [[0, CHUNK - 1], [CHUNK, binary.length - 1]]);
  const empty = adapterFixture(source, Buffer.alloc(0));
  assert.equal(empty.syncFetchFile('/owner/empty', 0).length, 0);
  assert.equal(empty.state.requests.length, 0, 'zero-length files must not request an invalid byte range');
  for (const mode of ['short', 'long', 'base64', 'http']) {
    const f = adapterFixture(source, Buffer.from('original')); f.state.mode = mode;
    assert.throws(() => f.syncFetchFile('/owner/bad', 8), /byte count mismatch|Invalid base64|HTTP 503/, mode);
  }
  const noDecoder = adapterFixture(source, Buffer.from('original')); noDecoder.scope.atob = undefined;
  assert.throws(() => noDecoder.syncFetchFile('/owner/bad', 8), /Base64 decoding is required/);
  const prefetch = adapterFixture(source, binary), lazy = prefetch.createRangeLazyContents('/owner/range', binary.length);
  prefetch.state.mode = 'short';
  await assert.rejects(lazy.prefetchChunk(0), /byte count mismatch/);
  prefetch.state.mode = 'valid'; await lazy.prefetchChunk(0);
  assert.deepEqual(Buffer.from(lazy.subarray(0, 10)), binary.subarray(0, 10));
  assert.equal(prefetch.state.requests.length, 0, 'failed prefetch must be retryable and validated bytes reusable');
  process.stdout.write('owner mounts: lossless bounded base64, exact lengths, empty files and failed-prefetch retry pass\n');

  const runtime = process.env.SOURCE_WASM_FS_FIXTURE || path.join(__dirname, '../web/source-engine.js');
  if (!fs.existsSync(runtime)) {
    process.stdout.write('owner mounts: SKIP actual MEMFS checks (set SOURCE_WASM_FS_FIXTURE to a retained source-engine.js)\n');
    return;
  }
  const module = await retainedFs(runtime), FS = module.FS;
  let sequence = 0;
  for (const kind of ['mountLazyWholeFile', 'mountRangeLazyFile']) {
    function mounted(original = Buffer.from('abcdef')) {
      const f = adapterFixture(source, original), dest = `/game/hl2/file-${sequence++}.bin`;
      const node = f[kind](module, dest, '/owner/file', original.length);
      return { ...f, dest, node, original };
    }
    const metadata = mounted();
    assert.equal(FS.stat(metadata.dest).size, 6);
    FS.chmod(metadata.dest, 0o644); FS.utime(metadata.dest, 1000, 2000);
    FS.truncate(metadata.dest, 6);
    assert.equal(metadata.state.requests.length, 0, 'stat, chmod, time and no-op truncate stay lazy');
    assert.deepEqual(Buffer.from(FS.readFile(metadata.dest)), Buffer.from('abcdef'));
    assert.equal(typeof metadata.node.contents.subarray, 'function');
    assert.equal(metadata.node.contents instanceof Uint8Array, false, 'ordinary reads keep lazy storage');
    const requestsBeforeWrite = metadata.state.requests.length;
    const opened = FS.open(metadata.dest, 'r+');
    assert.equal(FS.write(opened, Buffer.from('XY'), 0, 2, 2), 2);
    assert.deepEqual(Buffer.from(FS.readFile(metadata.dest)), Buffer.from('abXYef'));
    assert.equal(FS.write(opened, Buffer.from('!'), 0, 1, 6), 1);
    assert.equal(FS.stat(metadata.dest).size, 7);
    assert.deepEqual(Buffer.from(FS.readFile(metadata.dest)), Buffer.from('abXYef!'));
    assert.equal(metadata.state.requests.length, requestsBeforeWrite, 'first modification reuses fetched data; later writes never refetch');
    assert.equal(Object.getOwnPropertyDescriptor(metadata.node, 'usedBytes').writable, true);
    FS.ftruncate(opened.fd, 3); assert.deepEqual(Buffer.from(FS.readFile(metadata.dest)), Buffer.from('abX'));
    FS.ftruncate(opened.fd, 7); assert.deepEqual([...FS.readFile(metadata.dest)], [97, 98, 88, 0, 0, 0, 0]);
    FS.close(opened);

    const overwrite = mounted();
    FS.writeFile(overwrite.dest, Buffer.from('new'));
    assert.equal(overwrite.state.requests.length, 0, 'O_TRUNC discards owner content without downloading it');
    assert.deepEqual(Buffer.from(FS.readFile(overwrite.dest)), Buffer.from('new'));
    assert.equal(FS.stat(overwrite.dest).size, 3);

    const sparse = mounted();
    const stream = FS.open(sparse.dest, 'r+'); FS.write(stream, Buffer.from('Z'), 0, 1, 9); FS.close(stream);
    assert.deepEqual([...FS.readFile(sparse.dest)], [97, 98, 99, 100, 101, 102, 0, 0, 0, 90]);
    const append = mounted();
    const appendStream = FS.open(append.dest, 'a'); FS.write(appendStream, Buffer.from('!'), 0, 1); FS.close(appendStream);
    assert.deepEqual(Buffer.from(FS.readFile(append.dest)), Buffer.from('abcdef!'));

    const grown = mounted(); module.HEAPU8.set([88, 89], 32);
    const oldHeap = module.HEAPU8;
    grown.state.onSend = () => { module.growFixtureHeap(); grown.state.onSend = null; };
    const growStream = FS.open(grown.dest, 'r+'); FS.write(growStream, oldHeap, 32, 2, 1); FS.close(growStream);
    assert.equal(oldHeap.byteLength, 0, 'fixture grows native memory while lazy content is being fetched');
    assert.deepEqual(Buffer.from(FS.readFile(grown.dest)), Buffer.from('aXYdef'), 'COW snapshots the native write source before synchronous I/O');

    for (const size of [0, 3, 9]) {
      const truncate = mounted(); FS.truncate(truncate.dest, size);
      const expected = Buffer.alloc(size); Buffer.from('abcdef').copy(expected);
      assert.deepEqual(Buffer.from(FS.readFile(truncate.dest)), expected);
      assert.equal(FS.stat(truncate.dest).size, size);
      if (!size) assert.equal(truncate.state.requests.length, 0);
    }
    const failed = mounted(); failed.state.mode = 'short';
    const failedStream = FS.open(failed.dest, 'r+');
    assert.throws(() => FS.write(failedStream, Buffer.from('X'), 0, 1, 1), /byte count mismatch/);
    assert.equal(FS.stat(failed.dest).size, 6);
    failed.state.mode = 'valid';
    assert.deepEqual(Buffer.from(FS.readFile(failed.dest)), Buffer.from('abcdef'), 'failed materialization preserves original logical bytes');
    FS.close(failedStream);

    const mapped = mounted(); const mapStream = FS.open(mapped.dest, 'r+');
    const mapping = FS.mmap(mapStream, 6, 0, 3, 1);
    assert.deepEqual(Buffer.from(module.HEAPU8.subarray(mapping.ptr, mapping.ptr + 6)), Buffer.from('abcdef'));
    module.HEAPU8[mapping.ptr + 1] = 88;
    FS.msync(mapStream, module.HEAPU8.subarray(mapping.ptr, mapping.ptr + 6), 0, 6, 1);
    assert.deepEqual(Buffer.from(FS.readFile(mapped.dest)), Buffer.from('aXcdef'));
    FS.close(mapStream);
  }
  process.stdout.write('owner mounts: actual retained MEMFS lazy reads, metadata, COW writes/appends/sparse/overwrite, truncate/grow, failed modification and mmap/msync pass\n');
}

module.exports = run;
if (require.main === module) run().catch(error => { console.error(error); process.exitCode = 1; });
